### ISSUE TITLE
Hero Counters being displayed in a strange way?

### ISSUE THREAD

**Issue by JaneSmith** [VariantXYZ/PSO2ACT#93]
Hello. I'm not sure if this is the right place for this, but here we go. I've been using OverParse for a long time, and today wanted to dig deep into my Hero Counter damage _for each weapon_. But I could only see one "Hero Counter" in my damage logs, instead of the expected "Hero Counter (Sword)", "Hero Counter (TMG)", and "Hero Counter (Talis)".

Digging into the OverParse code, I found that it gets these from the "skills.csv" file, which it pulls from this repository - and digging into _that_ file, it looks like we have the following:

```
Sword Step Attack (Hero),2448594388,Melee,Hero Sword Step Attack
Hero Counter,2094998893,Melee,Hero Sword Step Attack after dodge (Hero Counter) (Hr skill)
TMG Step Attack (Hero),2834748182,Ranged,Hero TMG Step Attack
TMG Step Attack (Hero),1905792389,Ranged,Hero TMG Step Attack after dodge
Brand New Star,2832005595,PA,Brand New Star
Brand New Star,1399183080,PA,Brand New Star after dodge
Talis Step Attack (Hero),3318755300,Ranged,Hero Talis Step Attack
Talis Step Attack (Hero),1089593935,Ranged,Hero Talis Step Attack after dodge
Talis Step Attack (Hero),4105920492,Ranged,Hero Talis Step Attack after dodge
```

So, the problems I have here are:
1. There's an inconsistency between how the counters are displayed.
2. It's impossible to isolate the damage of TMG counters or Talis counters as they just get merged together with regular step attacks.
3. It's impossible to isolate the damage of Brand New Star counters, as it just gets merged together with the regular Brand New Star.

I'd like to propose changing the counter versions to "Hero Counter (Sword)", "Hero Counter (TMG)", "Brand New Star (Counter)", and "Hero Counter (Talis)".

Would this be okay? I don't know what the etiquette is here. It seems like an easy enough change for someone to do, or otherwise I could try and submit a pull request. Or would this be unwanted and you prefer it how it is currently for some reason?

**Comment by Sora3100** [comment]
Originally, even the Sword Counter was named "Sword Step Attack (Hero)" as well, but some people wanted to seperate them, so it was changed.

I don't see any issues with this either, so I'll make the requested changes.

**Comment by JaneSmith** [comment]
Thanks a lot!
